name: SpecialEventCommand
version: '${project.version}'
main: de.flashyboi.gamellounge.specialeventcommand.SpecialEventCommand
api-version: 1.17
authors: [ flash_btw ]
website: http://discord.gammellounge.de/
commands:
  event: